/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.managementkaskelas;

//tanggal
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.time.LocalDate;  
import java.time.temporal.ChronoUnit;
import javax.swing.JOptionPane;
//untuk gambar
import javax.imageio.ImageIO; 
import javax.swing.ImageIcon;
import java.awt.Image;
import java.io.IOException;
import java.io.InputStream;

/**
 *
 * @author ARDO
 */
public class main extends javax.swing.JFrame {
    private Connection con;
    private Statement stat;
    private ResultSet res;
    private int totalSaldo;
    LocalDate tanggalNow = LocalDate.now();
    
    public main() {
        initComponents();
        aturMinggu();
        connection();
        nama();
        saldo();
//        setUang();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    //aturMinggu() ini saya buat untuk menghitung sudah berapa minggu yang dilewati dari tanggal awal pembayaran (1 jan)
    private void aturMinggu() {
        
        LocalDate tanggalStart = LocalDate.of(2025, 1, 1);
        long jumlahMinggu = ChronoUnit.WEEKS.between(tanggalStart, tanggalNow);
        jumlahMinggu += 1;  //misal sudah lewat 2 minggu, berarti kita akan masuk ke pembayaran untuk minggu selanjutnya yaitu minggu ke-3
        mingguKe.setText("Pembayaran Minggu Ke-" + jumlahMinggu);
    }
    
    private void connection() {
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/managementKas", "root", "");
            stat = con.createStatement();
        } catch (ClassNotFoundException | SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    private void nama(){
        try {
            res = stat.executeQuery("SELECT * FROM mahasiswa");

            while (res.next()) {
                String nama1 = res.getString("nama");
                nama.addItem(nama1);
            }
            nama.setSelectedIndex(0); 

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }
    
    private void gambar() {
        try {
            res = stat.executeQuery("SELECT foto FROM mahasiswa WHERE nim = " + nimm.getText());

            if (res.next()) {
                InputStream is = res.getBinaryStream("foto");
                Image img = ImageIO.read(is);
                ImageIcon icon = new ImageIcon(img);
                pp.setIcon(icon);
            }else if (nama.getSelectedIndex() == 0){    //saya tidak tau kenapa ini tidak berpengaruh sama sekali:(
                pp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/managementkaskelas/We Heart It.jpg")));
            }
        } catch (IOException |SQLException e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }
    
    private void data() {
        try {
            res = stat.executeQuery("SELECT * FROM mahasiswa WHERE nama='" + nama.getSelectedItem() + "'" );
            while (res.next()) {
                nimm.setText(res.getString("nim"));
                
                //yg sdh dibayar
                int dibayar = res.getInt("total_pembayaran");
                dibayar *= 5000;
                totalSudah.setText("Rp. " + dibayar + ", 00");
                
                //atur minggu lagi, saya copas saja dari function diatas tadi buk
                LocalDate tanggalStart = LocalDate.of(2025, 1, 1);
                long jumlahMinggu = ChronoUnit.WEEKS.between(tanggalStart, tanggalNow);
                jumlahMinggu += 1;
                
                //yg hrs dbyr
                jumlahMinggu *= 5000;
                totalSemua.setText("Rp. " + jumlahMinggu + ", 00");
                int total = (int) jumlahMinggu;
                int kurang = total - dibayar;
                if (kurang >= 0) {
                    totalKurang.setText("Rp. " + kurang + ", 00");
                } else {
                    totalKurang.setText("Rp. 0, 00");
                }
                gambar();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }
    
    private void saldo() {
        try {
            //masuk
            res = stat.executeQuery("SELECT SUM(total_pembayaran) AS total FROM mahasiswa");
            int totalPembayaran = 0;

            if (res.next()) {
                totalPembayaran = res.getInt("total");
            }
            
            //keluar
            res = stat.executeQuery("SELECT SUM(jumlah) AS keluar FROM pengeluaran");
            int keluar = 0;

            if (res.next()) {
                keluar = res.getInt("keluar");
            }
            
            int uangMasuk = totalPembayaran * 5000;
            totalSaldo = uangMasuk - keluar;
            saldo.setText("Rp. " + totalSaldo + ",00");
            saldo1.setText("Rp. " + totalSaldo + ",00");
            pitihMasuak.setText("Rp. " + uangMasuk + ",00");
            pitihKalua.setText("Rp. " + keluar + ",00");

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    
//    private void masukKeluar(){
////        try{
////            res = stat.executeQuery("SELECT SUM(total_pemasukan)")
////        }
//    }    
    
    
//    private void terakhir() {
//        int terakhir = 0;
//        try{
//            res = stat.executeQuery("SELECT id FROM pemasukan ORDER BY id DESC LIMIT 1");
//            
//            if (res.next()){
//                terakhir = res.getInt("id");
//            }
//        } catch (SQLException e) {
//            JOptionPane.showMessageDialog(null, e);
//        }
//    }
    

        
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panel1 = new java.awt.Panel();
        label1 = new java.awt.Label();
        kGradientPanel1 = new com.k33ptoo.components.KGradientPanel();
        tabbedPaneCustom1 = new com.mycompany.managementkaskelas.TabbedPaneCustom();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        mingguKe = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel21 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        totalSudah = new javax.swing.JLabel();
        totalSemua = new javax.swing.JLabel();
        totalKurang = new javax.swing.JLabel();
        jPanel23 = new javax.swing.JPanel();
        jPanel24 = new javax.swing.JPanel();
        pp = new javax.swing.JLabel();
        jPanel25 = new javax.swing.JPanel();
        jPanel26 = new javax.swing.JPanel();
        nama = new javax.swing.JComboBox<>();
        nimm = new javax.swing.JLabel();
        jPanel22 = new javax.swing.JPanel();
        jPanel27 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel28 = new javax.swing.JPanel();
        jumlahBayar = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        submit = new javax.swing.JButton();
        reset = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        saldo = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jTextField2 = new javax.swing.JTextField();
        jPanel15 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jPanel16 = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        saldo1 = new javax.swing.JLabel();
        jPanel18 = new javax.swing.JPanel();
        jPanel19 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        pitihMasuak = new javax.swing.JLabel();
        jPanel20 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        pitihKalua = new javax.swing.JLabel();
        jPanel30 = new javax.swing.JPanel();
        jPanel31 = new javax.swing.JPanel();
        jToggleButton1 = new javax.swing.JToggleButton();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        panel1.setLayout(new java.awt.GridBagLayout());

        label1.setAlignment(java.awt.Label.CENTER);
        label1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        label1.setFont(new java.awt.Font("Ebrima", 1, 24)); // NOI18N
        label1.setText("APLIKASI MANAGEMENT KAS");
        panel1.add(label1, new java.awt.GridBagConstraints());

        kGradientPanel1.setkEndColor(new java.awt.Color(21, 87, 153));
        kGradientPanel1.setkStartColor(new java.awt.Color(21, 153, 87));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new java.awt.GridBagLayout());

        mingguKe.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        mingguKe.setText("Pembayaran Minggu Ke-0");
        mingguKe.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel3.add(mingguKe, new java.awt.GridBagConstraints());

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jPanel21.setBackground(new java.awt.Color(255, 255, 255));
        jPanel21.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel21.setLayout(new java.awt.GridLayout(2, 3));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Total Sudah Dibayar:");
        jPanel21.add(jLabel2);

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Total Seharusnya");
        jPanel21.add(jLabel4);

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Total Kekurangan");
        jPanel21.add(jLabel7);

        totalSudah.setFont(new java.awt.Font("Verdana", 3, 14)); // NOI18N
        totalSudah.setForeground(new java.awt.Color(13, 133, 73));
        totalSudah.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        totalSudah.setText("Rp. 0, 00");
        jPanel21.add(totalSudah);

        totalSemua.setFont(new java.awt.Font("Verdana", 3, 14)); // NOI18N
        totalSemua.setForeground(new java.awt.Color(249, 193, 28));
        totalSemua.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        totalSemua.setText("Rp. 0, 00");
        jPanel21.add(totalSemua);

        totalKurang.setFont(new java.awt.Font("Verdana", 3, 14)); // NOI18N
        totalKurang.setForeground(new java.awt.Color(153, 0, 0));
        totalKurang.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        totalKurang.setText("Rp. 0, 00");
        jPanel21.add(totalKurang);

        jPanel23.setBackground(new java.awt.Color(255, 255, 255));
        jPanel23.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel24.setBackground(new java.awt.Color(255, 255, 255));
        jPanel24.setLayout(new java.awt.GridLayout(1, 2));

        pp.setBackground(new java.awt.Color(255, 255, 255));
        pp.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        pp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/managementkaskelas/We Heart It.jpg"))); // NOI18N
        jPanel24.add(pp);

        jPanel25.setBackground(new java.awt.Color(255, 255, 255));
        jPanel25.setLayout(new java.awt.GridLayout(2, 1));

        jPanel26.setBackground(new java.awt.Color(255, 255, 255));

        nama.setEditable(true);
        nama.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        nama.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NAMA MAHASISWA" }));
        nama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel26Layout = new javax.swing.GroupLayout(jPanel26);
        jPanel26.setLayout(jPanel26Layout);
        jPanel26Layout.setHorizontalGroup(
            jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel26Layout.createSequentialGroup()
                .addComponent(nama, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel26Layout.setVerticalGroup(
            jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel26Layout.createSequentialGroup()
                .addComponent(nama, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel25.add(jPanel26);

        nimm.setBackground(new java.awt.Color(255, 255, 255));
        nimm.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nimm.setText("NIM");
        nimm.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel25.add(nimm);

        jPanel24.add(jPanel25);

        jPanel23.add(jPanel24);

        jPanel22.setLayout(new java.awt.GridLayout(3, 1));

        jPanel27.setBackground(new java.awt.Color(255, 255, 255));
        jPanel27.setLayout(new java.awt.GridBagLayout());

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Jumlah Pembayaran");
        jPanel27.add(jLabel8, new java.awt.GridBagConstraints());

        jPanel22.add(jPanel27);

        jPanel28.setBackground(new java.awt.Color(255, 255, 255));

        jumlahBayar.setEditable(true);
        jumlahBayar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", " " }));
        jPanel28.add(jumlahBayar);

        jLabel9.setText("Kali");
        jPanel28.add(jLabel9);

        jPanel22.add(jPanel28);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 30, 5));

        submit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/managementkaskelas/Bag-Dollar--Streamline-Core (1).png"))); // NOI18N
        submit.setText("Submit");
        submit.setPreferredSize(new java.awt.Dimension(90, 30));
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });
        jPanel5.add(submit);

        reset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/managementkaskelas/Triangle-Arrow-Rotate-Left-5--Streamline-Core.png"))); // NOI18N
        reset.setText("Reset");
        reset.setPreferredSize(new java.awt.Dimension(90, 30));
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });
        jPanel5.add(reset);

        delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/managementkaskelas/Recycle-Bin-1--Streamline-Core.png"))); // NOI18N
        delete.setText("Hapus");
        delete.setPreferredSize(new java.awt.Dimension(90, 30));
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        jPanel5.add(delete);

        exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/managementkaskelas/Delete-Square--Streamline-Core.png"))); // NOI18N
        exit.setText("Exit");
        exit.setPreferredSize(new java.awt.Dimension(90, 30));
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        jPanel5.add(exit);

        jPanel22.add(jPanel5);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel22, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 746, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jPanel21, javax.swing.GroupLayout.PREFERRED_SIZE, 743, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPanel23, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 743, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(72, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel21, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 755, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        tabbedPaneCustom1.addTab("Pemasukan", jPanel2);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray));
        jPanel7.setLayout(new java.awt.GridLayout(2, 1));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Saldo Tersedia:");
        jLabel1.setPreferredSize(new java.awt.Dimension(20, 20));
        jPanel7.add(jLabel1);

        saldo.setFont(new java.awt.Font("Verdana", 3, 14)); // NOI18N
        saldo.setForeground(new java.awt.Color(13, 133, 73));
        saldo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        saldo.setText("Rp. 0, 00");
        jPanel7.add(saldo);

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setLayout(new java.awt.GridBagLayout());

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray));
        jPanel9.setPreferredSize(new java.awt.Dimension(500, 300));

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel10.setLayout(new java.awt.GridLayout(1, 0));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Detail Pengeluaran");
        jLabel3.setPreferredSize(new java.awt.Dimension(200, 36));
        jPanel10.add(jLabel3);

        jPanel11.setLayout(new java.awt.GridLayout(1, 1, 20, 0));

        jPanel12.setBackground(new java.awt.Color(255, 255, 255));
        jPanel12.setLayout(new java.awt.GridLayout(5, 1, 0, 10));

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("Jumlah Penarikan");
        jLabel5.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel12.add(jLabel5);

        jPanel13.setBackground(new java.awt.Color(204, 204, 204));

        jTextField1.setBackground(new java.awt.Color(204, 204, 204));
        jTextField1.setFont(new java.awt.Font("Nirmala UI", 1, 24)); // NOI18N
        jTextField1.setText("0");
        jTextField1.setBorder(null);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel6.setText("Rp.");
        jLabel6.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTextField1)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel12.add(jPanel13);

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel10.setText("Tujuan ");
        jLabel10.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel12.add(jLabel10);

        jPanel14.setBackground(new java.awt.Color(255, 255, 255));

        jTextField2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        jTextField2.setSelectedTextColor(new java.awt.Color(242, 242, 242));
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE)
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        jPanel12.add(jPanel14);

        jPanel15.setBackground(new java.awt.Color(255, 255, 255));
        jPanel15.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 0));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/managementkaskelas/Credit-Card-2--Streamline-Core.png"))); // NOI18N
        jButton1.setText("Tarik");
        jButton1.setMaximumSize(new java.awt.Dimension(100, 50));
        jButton1.setPreferredSize(new java.awt.Dimension(100, 33));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel15.add(jButton1);

        jPanel12.add(jPanel15);

        jPanel11.add(jPanel12);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(108, Short.MAX_VALUE)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(116, 116, 116))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel8.add(jPanel9, new java.awt.GridBagConstraints());

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, 756, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        tabbedPaneCustom1.addTab("Pengeluaran", jPanel6);

        jPanel16.setBackground(new java.awt.Color(255, 255, 255));

        jPanel17.setBackground(new java.awt.Color(255, 255, 255));
        jPanel17.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray));
        jPanel17.setLayout(new java.awt.GridLayout(2, 1));

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Total Saldo:");
        jLabel11.setPreferredSize(new java.awt.Dimension(20, 20));
        jPanel17.add(jLabel11);

        saldo1.setFont(new java.awt.Font("Verdana", 3, 14)); // NOI18N
        saldo1.setForeground(new java.awt.Color(13, 133, 73));
        saldo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        saldo1.setText("Rp. 0, 00");
        jPanel17.add(saldo1);

        jPanel18.setBackground(new java.awt.Color(255, 255, 255));
        jPanel18.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray));
        jPanel18.setLayout(new java.awt.GridLayout(1, 2));

        jPanel19.setBackground(new java.awt.Color(255, 255, 255));
        jPanel19.setLayout(new java.awt.GridLayout(2, 1));

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Total Pemasukan:");
        jLabel12.setPreferredSize(new java.awt.Dimension(20, 20));
        jPanel19.add(jLabel12);

        pitihMasuak.setFont(new java.awt.Font("Verdana", 3, 14)); // NOI18N
        pitihMasuak.setForeground(new java.awt.Color(255, 178, 0));
        pitihMasuak.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pitihMasuak.setText("Rp. 0, 00");
        jPanel19.add(pitihMasuak);

        jPanel18.add(jPanel19);

        jPanel20.setBackground(new java.awt.Color(255, 255, 255));
        jPanel20.setLayout(new java.awt.GridLayout(2, 1));

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Total Pengeluaran:");
        jLabel13.setPreferredSize(new java.awt.Dimension(20, 20));
        jPanel20.add(jLabel13);

        pitihKalua.setFont(new java.awt.Font("Verdana", 3, 14)); // NOI18N
        pitihKalua.setForeground(new java.awt.Color(153, 0, 0));
        pitihKalua.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pitihKalua.setText("Rp. 0, 00");
        jPanel20.add(pitihKalua);

        jPanel18.add(jPanel20);

        jPanel30.setBackground(new java.awt.Color(255, 255, 255));

        jPanel31.setBackground(new java.awt.Color(255, 255, 255));

        jToggleButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/managementkaskelas/Logout-1--Streamline-Core.png"))); // NOI18N
        jToggleButton1.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jToggleButton1.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        jPanel31.add(jToggleButton1);

        jPanel30.add(jPanel31);

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel18, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 756, Short.MAX_VALUE)
                    .addComponent(jPanel30, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addContainerGap(85, Short.MAX_VALUE)
                .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jPanel18, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jPanel30, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57))
        );

        tabbedPaneCustom1.addTab("Saldo", jPanel16);

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(tabbedPaneCustom1, javax.swing.GroupLayout.PREFERRED_SIZE, 773, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(tabbedPaneCustom1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, 806, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(kGradientPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        try {
            res = stat.executeQuery("SELECT * FROM mahasiswa WHERE nama='" + nama.getSelectedItem() + "'" );
            int sudahDibayar = 0;
            if (res.next()) {
                sudahDibayar = res.getInt("total_pembayaran");
            }
            int jumlahBayarr = Integer.parseInt(jumlahBayar.getSelectedItem().toString());
            int pembayaran = sudahDibayar + jumlahBayarr;
            stat.executeUpdate("UPDATE mahasiswa SET total_pembayaran = " + pembayaran + " WHERE nama='" + nama.getSelectedItem() + "'");
            JOptionPane.showMessageDialog(rootPane, "Senyum, dan Ucapkan Terimakasih Kepada " + nama.getSelectedItem());
            data();
            saldo();
        } catch (HeadlessException | NumberFormatException | SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }

    }//GEN-LAST:event_submitActionPerformed

    private void namaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaActionPerformed
        data();        
    }//GEN-LAST:event_namaActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        nama.setSelectedIndex(0);
        pp.setIcon(null);
        nimm.setText("NIM");
        totalSudah.setText("Rp. 0, 00");
        totalSemua.setText("Rp. 0, 00");
        totalKurang.setText("Rp. 0, 00");
        pp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/managementkaskelas/We Heart It.jpg")));

    }//GEN-LAST:event_resetActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        int ya = JOptionPane.showConfirmDialog(null, "Hapus " + jumlahBayar.getSelectedItem() + " Kali Pembayaran dari " + nama.getSelectedItem() + "?", "Konfirmasi Penghapusan!", JOptionPane.YES_NO_OPTION);
        
        if (ya == JOptionPane.YES_OPTION) {
            try {
                res = stat.executeQuery("SELECT * FROM mahasiswa WHERE nama='" + nama.getSelectedItem() + "'" );
                int sudahDibayar = 0;
                if (res.next()) {
                    sudahDibayar = res.getInt("total_pembayaran");
                }
                int jumlahBayarr = Integer.parseInt(jumlahBayar.getSelectedItem().toString());
                int pembayaran = sudahDibayar - jumlahBayarr;
                stat.executeUpdate("UPDATE mahasiswa SET total_pembayaran = " + pembayaran + " WHERE nama='" + nama.getSelectedItem() + "'");
                JOptionPane.showMessageDialog(rootPane, jumlahBayar.getSelectedItem() + " Kali Pembayaran dari " + nama.getSelectedItem() + " Berhasil Dihapus!");
                data();
                saldo();
            } catch (HeadlessException | NumberFormatException | SQLException e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_deleteActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int penarikann = Integer.parseInt(jTextField1.getText());
        String tujuann = jTextField2.getText();
        if (totalSaldo < penarikann){
            JOptionPane.showMessageDialog(rootPane, "Jumlah Pengeluaran Tidak Boleh Melebihi Total Saldo yang Tersedia!");
        } else if (tujuann.isEmpty() && penarikann == 0){
            JOptionPane.showMessageDialog(rootPane, "Masukkan Jumlah dan Tujuan!");
        } else if (tujuann.isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "Masukkan Tujuan!");
        } else if (penarikann == 0){
            JOptionPane.showMessageDialog(rootPane, "Masukkan Jumlah yang Benar!");
        } else {
            String keluar = jTextField1.getText(); 
            try {
                stat.executeUpdate("INSERT INTO pengeluaran (jumlah, tanggal, tujuan) VALUES ('" + penarikann + "', '" + tanggalNow + "', '" + tujuann + "')");
                JOptionPane.showMessageDialog(rootPane,"Rp. " + keluar + ",00 Telah Dicatat Sebagai Pengeluaran!");
                saldo();
            } catch (HeadlessException | NumberFormatException | SQLException e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton delete;
    private javax.swing.JButton exit;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel27;
    private javax.swing.JPanel jPanel28;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel30;
    private javax.swing.JPanel jPanel31;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JComboBox<String> jumlahBayar;
    private com.k33ptoo.components.KGradientPanel kGradientPanel1;
    private java.awt.Label label1;
    private javax.swing.JLabel mingguKe;
    private javax.swing.JComboBox<String> nama;
    private javax.swing.JLabel nimm;
    private java.awt.Panel panel1;
    private javax.swing.JLabel pitihKalua;
    private javax.swing.JLabel pitihMasuak;
    private javax.swing.JLabel pp;
    private javax.swing.JButton reset;
    private javax.swing.JLabel saldo;
    private javax.swing.JLabel saldo1;
    private javax.swing.JButton submit;
    private com.mycompany.managementkaskelas.TabbedPaneCustom tabbedPaneCustom1;
    private javax.swing.JLabel totalKurang;
    private javax.swing.JLabel totalSemua;
    private javax.swing.JLabel totalSudah;
    // End of variables declaration//GEN-END:variables
}
